# 1. What is a Python library? Why ^o we use Python libraries?

Python library is a prewritten collection of modules or packages. that we can directly use in a programe just by importing.
we use python library for code Reusability,Efficiency,Rapid Development etc

## 2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but they have several key differences in terms of functionality, performance, and usage. Here are some of the main distinctions:

Data Type:

List: A Python list can contain elements of different data types. It can hold integers, floats, strings, and even other lists.
NumPy Array: NumPy arrays are homogeneous, meaning all elements in the array must be of the same data type. This homogeneity allows for more efficient storage and operations.
Performance:

List: Lists are generally slower than NumPy arrays when it comes to mathematical operations and other array-related computations.
NumPy Array: NumPy arrays are optimized for numerical operations and are much faster than lists for such tasks. NumPy is implemented in C and Fortran, which contributes to its performance.
Memory Efficiency:

List: Lists consume more memory as they store additional information (type information for each element) and are less space-efficient.
NumPy Array: NumPy arrays are more memory-efficient because they are homogeneous and use contiguous blocks of memory.
Ease of Use:

List: Lists are more flexible and easier to work with for general-purpose tasks due to their dynamic nature and versatility.
NumPy Array: NumPy arrays are specialized for numerical operations, and their syntax is often more concise and expressive for mathematical computations.
Functionality:

List: Lists offer a broad range of methods and functionalities, but they may not be as efficient as NumPy for numerical computations.
NumPy Array: NumPy provides a variety of mathematical functions and operations that are optimized for array processing. It includes functionality similar to MATLAB for scientific computing.
Broadcasting:

List: Lists don't support broadcasting, which allows operations on arrays of different shapes and sizes without the need for explicit loops.
NumPy Array: NumPy arrays support broadcasting, making it easier to perform operations on arrays of different shapes.
In summary, while lists are versatile and suitable for general-purpose tasks, NumPy arrays are designed for efficient numerical computations and offer advantages in terms of performance and memory efficiency. The choice between them depends on the specific requirements of the task at hand.








## 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
shape=arr.shape
size = arr.size
dimention = arr.ndim

In [10]:
print(size)
print(shape)
print(dimention)

12
(3, 4)
2


# 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
fristRow = arr1[0,:]
fristRow

array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [17]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

element=arr1[2,3]

In [18]:
element

12

## 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [25]:
arr1 = np.array([[1, 2, 3, 4,11,12], [5, 6, 7, 8,12,34], [9, 10, 11, 12,15,45]])

odd_indexed_elements = arr1[:,1::2]

In [26]:
odd_indexed_elements


array([[ 2,  4, 12],
       [ 6,  8, 34],
       [10, 12, 45]])

# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [28]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.04439948 0.85673185 0.27298257]
 [0.79558227 0.18975544 0.81822323]
 [0.81158306 0.23798841 0.74817567]]


# 8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand: Generates random values from a uniform distribution between 0 (inclusive) and 1 (exclusive). All values are equally likely.

np.random.randn: Generates random values from a standard normal distribution (mean 0, standard deviation 1). Values are more likely to be close to 0, and the distribution follows a bell curve.

# 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [29]:
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
expanded_array = np.expand_dims(original_array, axis=2)

print("Original Array:")
print(original_array)

print("\nExpanded Array:")
print(expanded_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded Array:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


# 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [30]:
arr1 = np.array([[1, 2, 3, 4,11,12], [5, 6, 7, 8,12,34], [9, 10, 11, 12,15,45]])

arr1T= arr1.T

In [31]:
arr1T


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12],
       [11, 12, 15],
       [12, 34, 45]])

# 11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1


In [32]:
# INdex wiLe multiplicatio'

In [33]:
arr1 = arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2 = arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [35]:
# index wise multiplication

indMul = arr1*arr2
indMul

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [38]:
# matrix Multiplication

matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[7, 8], [9, 10], [11, 12]])

MatMul = matrix_A @ matrix_B
MatMul

array([[ 58,  64],
       [139, 154]])

In [40]:
# Add Both matrix

additionMatrix = arr1+arr2
additionMatrix

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [41]:
subMatrix = arr1-arr2
subMatrix 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
divMatrix = arr1/arr2
divMatrix 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12. Which function in Numpy can be used to swap the byte order of an array?

In [43]:
# np.ndarray.byteswap()

# 13. What is the significance of the np.linalg.inv function?


The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in its application in solving systems of linear equations and various linear algebraic operations.

# 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data. It returns a new array with the specified shape. The reshaping can be performed as long as the total number of elements in the array remains the same.

# 15 What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes and sizes to be combined in arithmetic operations. It enables operations between arrays that would otherwise be incompatible due to their differing shapes, without the need for explicit looping or resizing.

The fundamental concept behind broadcasting is to extend smaller arrays so that they have compatible shapes for arithmetic operations. This extension is done implicitly by NumPy, making it a convenient and efficient way to perform element-wise operations on arrays of different shapes.